### ISSUE TITLE
Difficulties in installing the 3dm Import Module

### ISSUE THREAD

**Issue by dshguilherme** [orbingol/rw3dm#1]
**Describe the bug**
CMake 3.13.2 gives out Error when following the Installing procedure.

**To Reproduce**
1. Downloaded the repository to a local file, under a custom name
2. Updated the submodules using Git Bash
3. CMake gives out Error: "Error in configuration process, project files may be invalid"
![image](https://user-images.githubusercontent.com/33161983/51121336-5cf1e700-17fe-11e9-879a-e8324c7449c1.png)

**Comment by orbingol** [comment]
@dshguilherme could you please post the CMake logs too?

**Comment by dshguilherme** [comment]
Log only says:
![image](https://user-images.githubusercontent.com/33161983/51125955-0938cb00-1809-11e9-882c-f2c867b4278a.png)

**Comment by orbingol** [comment]
Could you also post the logs in the CMake GUI too? I can only see "Configuring incomplete" part on the screenshot.

I have also some preliminary guesses for the solution:

1. Please make sure that you have `CMakeLists.txt` file in the `C:/Doutorado` directory? (I see the directory name on the screenshot)
2. Sometimes it is possible to get permission errors when you try to create a build directory on your Windows desktop using a non-Microsoft application. The best solution is choosing some other directory outside your Desktop or Documents. Definitely there is a fix for that but I don't remember it right now (sorry). I usually create the `build` directory inside the cloned repo directory. That directory is ignored using .gitignore.
3. Please make sure that you picked "Visual Studio 2017 64-bit" from the list of compilers. CMake can be a little bit confusing on that.

**Comment by dshguilherme** [comment]
After tweaking a lot with CMake (I was missing some key Visual Basic packages), I'm currently now stuck with CMake/Python problems. Namely this: 
![image](https://user-images.githubusercontent.com/33161983/51178603-338e9500-18aa-11e9-8aae-d707b83f2967.png)
Uploading Output Log:
[CMakeOutput.log](https://github.com/orbingol/rw3dm/files/2759465/CMakeOutput.log)

**Comment by orbingol** [comment]
It seems pybind11 isn't able to detect a cpython interpreter: https://github.com/pybind/pybind11/blob/9a19306fbf30642ca331d0ec88e7da54a96860f9/tools/FindPythonLibsNew.cmake#L96

Additionally, it seems a decent problem though: https://github.com/pybind/pybind11/issues/236

I will see what I can do (however, I don't think I can do anything to fix a pybind11 issue) but in the meantime, you can try the following super simple solutions. Please note that these super simple solutions don't mean they are correct:

Solution 1:

* Add Python and Python\scripts directories to the system path
* Open a command prompt or powershell instance
* Write "python" and then "pip"
* If you are not getting file not found errors, then you are good. Otherwise, check system path.
* Restart CMake, clean CMake variables
* Rerun CMake

Solution 2:
 
* Refer to this solution: https://github.com/pybind/pybind11/issues/236#issuecomment-225398379
* You will find the file here: 3rdparty/pybind11/tools/FindPythonLibsNew.cmake

**Comment by dshguilherme** [comment]
Solution 1 worked and make CMake run! Great. Now to work on those Rhino -> NURBS-Python... :)

Thanks a lot!

**Comment by orbingol** [comment]
It is good to know that you figured it out :)

**Comment by dshguilherme** [comment]
Now, after installing it, I get AttributeError: module 'rw3dm' has no attribute 'read'.
So I tried opening the module and to my surprise it is a bunch of nonsense.
![image](https://user-images.githubusercontent.com/33161983/51196443-46b75a00-18d6-11e9-9cdc-85ffa4799699.png)
I'm starting to think that the best way is to scan points over my geometry and interpolate them...

**Comment by orbingol** [comment]
That's a binary file actually :) and it looks like a Python egg file, i.e. a zipped module. It should work fine, though.

By looking at the error, I suspect that you might be using a different python version than you compiled the module for. That also happens when you compile the Python module with **Debug** option selected in Visual Studio. Please try to compile it with **Release** option selected.

**Comment by orbingol** [comment]
I am reopening this issue as I have found a problem in generation of Python wheel files and fixed it with the release of `v1.1.0`. I have also added the ability to call `from rw3dm import *` import statement (after the installation of course).

@dshguilherme could you please check it again with the latest updates?

**Comment by dshguilherme** [comment]
When running setup.py it gives errors:
![image](https://user-images.githubusercontent.com/33161983/51246378-7f584180-1971-11e9-96b7-9a638756bd29.png)

**Comment by orbingol** [comment]
What I see from the screenshot is that

1. You are using Debug version. Have you installed or really intended to use Python's debug version? If so, you might not be aware that you will end up compiling pretty much every single module you want to use. Please choose **Release** from the drop-down menu in VS2017 before starting to compile the module (I guess you missed it here: https://github.com/orbingol/rw3dm/issues/1#issuecomment-454486376)
2. Although the first solution should solve everything, it is always recommended to delete CMake build folder if you are constantly getting errors. This could be considered as the first rule of debugging with CMake.

I haven't added any information to choose **Release** version as some people might actually want to debug the module to add more features. Python's debug and regular versions are different, different module names and even different interpreters and it is possible to debug CPython modules with Visual Studio (and gdb, if you would like to accept the challenge :))

In any case, `python setup.py develop` or its pip counterpart should also work fine but you shouldn't delete the module installation directory.

**Comment by dshguilherme** [comment]
I have select the Release in VS2017 now, and went through with the installation. Still, rw3dm doesn't seem to have any methods, as per the picture.
![image](https://user-images.githubusercontent.com/33161983/51256627-fea73e80-198c-11e9-9fde-ec4ea90fc1e9.png)

**Comment by dshguilherme** [comment]
FIXED. Apparently I was missing the "from rw3dm import rw3dm". Not it finally works!

Thanks for being patient and helping me along this :) I'll surely cite rw3dm and NURBS-Python on my publications and properly thank you in the works.

**Comment by orbingol** [comment]
Well, the imports can be confusing :) Additionally, `from rw3dm import *` should also work fine. Then, you will be able to use `rw3dm.read()` directly.

I guess it is all resolved, right?
